### PR TITLE
432 new feature willard chandler density parameter

### PR DESCRIPTION
**Pull request by Marcello-Sega**
The Willard Chandler method takes a parameter _c_ that defines the density to use to describe the isosurface. In Pytim, this defaults to the average of the minimum and maximum density. However, sometimes one might want to use a different value, so I've just added an argument to the `WillardChandler` class so we can!

I also deleted `.travis.yml.`, which you can undo if you'd like. I wasn't able to clone the repository on Windows because the file name is invalid. I suspect it should be `.travis.yml` (without the trailing `.`), so it probably needs renaming anyway.

Please make sure that your pull request satisfies the following requirements:

#### If you have written a new method in one of the available modules

  - [x] Document it with a docstring
  - [ ] Add a short, deterministic test in the docstring 
  - [x] Explain briefly what the patch is about in the pull request

Please let me know if you want me to add another test to the docstring; it might make it a bit lengthy.

### CODE REVIEW

**Comment by Marcello-Sega** [comment]
@a-ws-m could you do your changes on this PR? If you don't have time let me know, I can take care. Thanks!

**Comment by a-ws-m** [comment]
@Marcello-Sega I'm away for a week but I can do them when I'm back :)

**Comment by Marcello-Sega** [comment]
No worries, then I'll take care of it.

**Comment by Marcello-Sega** [comment]
I've decided to add a a surface layer identification mechanism for the Willard Chandler method, I will include the docstring test in that pull request linked to  #434

**Pull request merged**
