### PR TITLE
Fixed issue with centering

### PR DESCRIPTION
**Pull request by balazsfabian**
Fixed the bug in universe.atoms.pack_into_box(). I don't know, why this wasn't caught earlier, because it was the matter of a simple doc-test. The function either needs all information about the box (the dimensions and tilt angles), or none, and it figures out by checking the data in the universe.

Also, the version in sanity check is taken from version.py now.

### CODE REVIEW

**Comment by balazsfabian** [comment]
As far as I see, there are formatting issues in the doctest brought about by a version change in numpy that affected the printing format.

**Comment by Marcello-Sega** [comment]
mhhh... yes, look at this:

    >>> import numpy as np 
    >>> print(np.__version__)  
    1.15.3
    >>> print(np.arange(0,3.))  
    [0. 1. 2.]
    >>> np.set_printoptions(legacy='1.13') 
    >>> print(np.arange(0,3.))  
    [ 0.  1.  2.]

**Comment by balazsfabian** [comment]
Shall we require a more recent numpy, or shall we add 
`np.set_printoptions(legacy='1.13')`
to every example? I'd prefer the first

**Comment by Marcello-Sega** [comment]
I'd also prefer that. However, it seems that also with numpy 1.15.x the problem persists. 
When running the test from the python shell, everything is ok. 
When runing the script from nosetest, instead, the formatting problem shows up.

**Comment by Marcello-Sega** [comment]
update: the issue seems to be stemming from 

    from skimage import measure

in `willard_chandler.py`

Looking for a clean workaround...

**Comment by Marcello-Sega** [comment]
merged in #296

**Pull request closed without merging**
